# El nombre de nuestro servidor
spring.application.name=finance-eureka-server

# El puerto estándar y oficial para Eureka es el 8761
server.port=8761

# Como este ES el servidor, le decimos que NO intente registrarse consigo mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false